version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: us-east-1
    ACCOUNT_ID: 495599769710
    IMAGE_REPO_NAME: brain-tasks-app
    IMAGE_TAG: latest
    CLUSTER_NAME: brain-tasks-cluster

phases:
  install:
    commands:
      - curl -o "https://dl.k8s.io/release/v1.27.0/bin/linux/amd64/kubectl"
      - chmod +x kubectl
      - mv kubectl /usr/local/bin/

  pre_build:
    commands:
      - echo Logging into ECR
      - REPO_URI=$ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $REPO_URI

  build:
    commands:
      - echo Building Docker image
      - docker build -t $IMAGE_REPO_NAME .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $REPO_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo Push image
      - docker push $REPO_URI:$IMAGE_TAG

      - echo Configure kubectl
      - aws eks update-kubeconfig --name $CLUSTER_NAME --region $AWS_DEFAULT_REGION

      - echo Deploy to EKS
      - kubectl apply -f deployment.yaml
      - kubectl apply -f service.yaml

artifacts:
  files:
    - '**/*'
